AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  eliminausuarioverifica:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::301300765385:role/service-role/elimina_usuario_verifica-role-p8fm5fac
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /usuarios
            Method: DELETE
      Environment:
        Variables:
          usuarios: usuarios_verifica
